version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spechofy_music_db
    restart: always
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
      POSTGRES_DB: music_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  music-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spechofy_music_service
    depends_on:
      - postgres
    ports:
      - "7272:7272"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://spechofy_music_db:5432/music_db
      SPRING_DATASOURCE_USERNAME: music_user
      SPRING_DATASOURCE_PASSWORD: music_password

volumes:
  postgres_data:
