version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spechofy_music_db
    restart: always
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
      POSTGRES_DB: music_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_music_db.sql:/docker-entrypoint-initdb.d/init_music_db.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
